// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAj73x7BMm8NfaXHij5UPG5Ey0e_WlLjDI',
    appId: '1:224989718582:ios:0e785206707ba842725097',
    messagingSenderId: '224989718582',
    projectId: 'healthtestbooking-1809',
    storageBucket: 'healthtestbooking-1809.appspot.com',
    iosBundleId: 'com.example.helthtestbookingapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB-vSQHmYeGh0nt4Hol2M9iBrn7rGJPIEU',
    appId: '1:224989718582:web:37fa806eeb66888a725097',
    messagingSenderId: '224989718582',
    projectId: 'healthtestbooking-1809',
    authDomain: 'healthtestbooking-1809.firebaseapp.com',
    storageBucket: 'healthtestbooking-1809.appspot.com',
    measurementId: 'G-L7FHDT6C2E',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB-vSQHmYeGh0nt4Hol2M9iBrn7rGJPIEU',
    appId: '1:224989718582:web:37fa806eeb66888a725097',
    messagingSenderId: '224989718582',
    projectId: 'healthtestbooking-1809',
    authDomain: 'healthtestbooking-1809.firebaseapp.com',
    storageBucket: 'healthtestbooking-1809.appspot.com',
    measurementId: 'G-L7FHDT6C2E',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAj73x7BMm8NfaXHij5UPG5Ey0e_WlLjDI',
    appId: '1:224989718582:ios:0e785206707ba842725097',
    messagingSenderId: '224989718582',
    projectId: 'healthtestbooking-1809',
    storageBucket: 'healthtestbooking-1809.appspot.com',
    iosBundleId: 'com.example.helthtestbookingapp',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAnwntWWrqdDAOt-eLohnUVV55h2LTI1Vc',
    appId: '1:224989718582:android:db95ae12c891b77c725097',
    messagingSenderId: '224989718582',
    projectId: 'healthtestbooking-1809',
    storageBucket: 'healthtestbooking-1809.appspot.com',
  );

}