name: helthtestbookingapp
description: "A new Flutter project."

# Prevent accidental publishing to pub.dev.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  http: ^1.2.2
  intl_phone_field: ^3.2.0
  firebase_core: ^3.6.0
  firebase_auth: ^5.3.1
  cloud_firestore: ^5.4.4
  google_fonts: ^6.2.1
  google_sign_in: ^6.2.1
  font_awesome_flutter: ^10.7.0
  image_picker: ^1.1.2
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  wolt_modal_sheet: ^0.9.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0
  

flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/images/